spring:  datasource:    url: jdbc:mysql://192.168.1.5:3306/test?characterEncoding=utf-8&useSSL=false&serverTimezone=GMT%2B8    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root  jpa:    database: mysql
    hibernate:      naming:        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
eureka:  client:    service-url:
      defaultZone: http://EurekaServerA:8761/eureka/,http://EurekaServerB:8762/eureka/
    register-with-eureka: true
    fetch-registry: true  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ip-address}:${spring.application.name}:${server.port}:@project.version@